# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattingStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('g', models.IntegerField()),
                ('pa', models.IntegerField()),
                ('ab', models.IntegerField()),
                ('r', models.IntegerField()),
                ('h', models.IntegerField()),
                ('_2b', models.IntegerField()),
                ('_3b', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('rbi', models.IntegerField()),
                ('sb', models.IntegerField()),
                ('cs', models.IntegerField()),
                ('bb', models.IntegerField()),
                ('so', models.IntegerField()),
                ('ba', models.FloatField()),
                ('obp', models.FloatField()),
                ('slg', models.FloatField()),
                ('ops', models.FloatField()),
                ('tb', models.IntegerField()),
                ('gdp', models.IntegerField()),
                ('hbp', models.IntegerField()),
                ('sh', models.IntegerField()),
                ('sf', models.IntegerField()),
                ('ibb', models.IntegerField()),
            ],
        ),
    ]
