# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 17:31
from __future__ import unicode_literals

from django.db import migrations
import csv
from swallows_app.models import BattingStats


def create_data(apps, schema_editor):
    with open('/Users/brennon/PycharmProjects/yakult_swallows/player_data') as infile:
        file_reader = csv.reader(infile)
        rows = [row for row in file_reader]
        batting_data = rows[1:]

    for row in batting_data:
        player_stats = BattingStats()
        player_stats.f_name = row[0]
        player_stats.l_name = row[1]
        player_stats.age = row[2]
        player_stats.g = row[3]
        player_stats.pa = row[4]
        player_stats.ab = row[5]
        player_stats.r = row[6]
        player_stats.h = row[7]
        player_stats._2b = row[8]
        player_stats._3b = row[9]
        player_stats.hr = row[10]
        player_stats.rbi = row[11]
        player_stats.sb = row[12]
        player_stats.cs = row[13]
        player_stats.bb = row[14]
        player_stats.so = row[15]
        player_stats.ba = row[16]
        player_stats.obp = row[17]
        player_stats.slg = row[18]
        player_stats.ops = row[19]
        player_stats.tb = row[20]
        player_stats.gdp = row[21]
        player_stats.hbp = row[22]
        player_stats.sh = row[23]
        player_stats.sf = row[24]
        player_stats.ibb = row[25]
        player_stats.save()

class Migration(migrations.Migration):

    dependencies = [
        ('swallows_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
