# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 17:31
from __future__ import unicode_literals

from django.db import migrations
import csv

def create_data(apps, schema_editor):
    with open('player_data') as infile:
        file_reader = csv.reader(infile)
        rows = [row for row in file_reader]
        headers = rows[0]
        batting_data = rows[1:]

    BattingStats = apps.get_model("swallows_app", "BattingStats")
    for row in batting_data:
        BattingStats.objects.create(**dict(zip(headers, row)))

class Migration(migrations.Migration):

    dependencies = [
        ('swallows_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
