# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swallows_app', '0002_auto_20160222_1939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BattingStats',
            new_name='BattingStat',
        ),
    ]
